### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by stas** [malthe/pq#3]
We should setup either a travis or solano CI to make sure the builds are passing always.

**Comment by jeanphix** [comment]
@malthe The `.travis.yml` works, should be easy to setup the project at https://travis-ci.org/

**Comment by malthe** [comment]
@stas how come the build is broken right now?

I tried adding "wheel" to test dependencies, since it complains about "bdist_wheel" not being available, but this doesn't fix the issue.

**Comment by stas** [comment]
@malthe looks like some issue with the Github's runners setup, #52 should fix it.
