### ISSUE TITLE
Should len(queue) skip items scheduled in the future?

### ISSUE THREAD

**Issue by migurski** [malthe/pq#6]
I’d like to use `len(queue)` to determine the size of a worker pool. Currently, [`Queue._count()` returns the count of all tasks](https://github.com/malthe/pq/blob/9b16991ca08b198fc8eacb4e6d660054fae7f46f/pq/__init__.py#L315) including those scheduled in the future. This is different from the number of tasks currently available for work.

Can or should `len(queue)` be modified to count only tasks available to a worker? The addition of one conditional to [the WHERE clause](https://github.com/malthe/pq/blob/9b16991ca08b198fc8eacb4e6d660054fae7f46f/pq/__init__.py#L319) should be sufficient:

    SELECT COUNT(*) FROM %(table)s
    WHERE q_name = %(name)s AND dequeued_at IS NULL
      AND (schedule_at IS NULL OR schedule_at <= NOW())

**Comment by malthe** [comment]
I think that's a very valid change, yes.
